Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,35 +1,34 @@
-name: Sync Fork
+name: Upstream Sync
+
+permissions:
+    contents: write
 
 on:
-  schedule:
-    - cron: '0 0 * * *'  # 每天午夜运行一次
-  workflow_dispatch:  # 允许手动触发
+    schedule:
+        - cron: "0 0 * * 5"
+    workflow_dispatch:
 
 jobs:
-  sync:
-    runs-on: ubuntu-latest
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
 
-    steps:
-    - name: Checkout fork
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0  # 获取完整的提交历史
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
 
-    - name: Configure Git
-      run: |
-        git config --global user.name "github-actions[bot]"
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+                  upstream_sync_repo: demoshang/siyuan-patch
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
 
-    - name: Fetch upstream
-      run: |
-        git remote add upstream github.com/demoshang/siyuan-patch.git
-        git fetch upstream
-
-    - name: Merge upstream
-      run: |
-        git checkout main
-        git merge upstream/main --ff-only
-
-    - name: Push changes
-      run: |
-        git push origin main
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
